$now = $(Get-Date).ToUniversalTime()
$begintoday = $(Get-Date -Hour 0 -Minute 0 -Second 0)
$timesincemidnight = New-TimeSpan -Start $begintoday -End $now
[int]$5minperiods = $timesincemidnight.TotalMinutes / 5
Write-Output "$5minperiods five-minute periods elapsed since midnight."
Write-Output "Please examine the groups of output generated by this script-based action"
Write-Output "All computers in sync (+/- 5 min) should appear in the same output group"
